name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "25.8.2"
          cache: true
      - run: vp install
      - run: vp check
      - run: vp test
      - run: vp build
